package pjctgame;

import javax.swing.JOptionPane;

public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        player = new javax.swing.JTextField();
        novoJogo = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        backInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCT GAME");
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Alpha 1.0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(634, 190, 60, 15);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 120)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PJCT GAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 800, 190);

        player.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        player.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player.setText("Player");
        player.setToolTipText("Digite o seu nome de jogador.");
        player.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerActionPerformed(evt);
            }
        });
        getContentPane().add(player);
        player.setBounds(230, 340, 340, 50);

        novoJogo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        novoJogo.setText("Novo Jogo");
        novoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoJogoActionPerformed(evt);
            }
        });
        getContentPane().add(novoJogo);
        novoJogo.setBounds(310, 420, 190, 30);

        sair.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(310, 520, 190, 30);

        backInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/start.png"))); // NOI18N
        backInicial.setAlignmentY(0.0F);
        backInicial.setBorder(null);
        backInicial.setBorderPainted(false);
        backInicial.setContentAreaFilled(false);
        backInicial.setFocusPainted(false);
        backInicial.setFocusable(false);
        backInicial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backInicial.setName(""); // NOI18N
        backInicial.setRequestFocusEnabled(false);
        backInicial.setRolloverEnabled(false);
        backInicial.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(backInicial);
        backInicial.setBounds(0, 0, 800, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void novoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoJogoActionPerformed
        JOptionPane.showMessageDialog(null, "Para saber como jogar, você pode clicar no botão ? na parte inferior do mapa.");
        Mapa abrirmapa = new Mapa(); //Cria uma classe Mapa.
        abrirmapa.show(); //Mostra a classe mapa.
        dispose();//Fecha o frame atual (MenuInicial).
    }//GEN-LAST:event_novoJogoActionPerformed

    private void playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton novoJogo;
    public static javax.swing.JTextField player;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
