
package pjctgame;

public class MenuMochila extends javax.swing.JDialog {

    /**
     * Creates new form MenuMochila
     */
    public MenuMochila(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //Centraliza a tela ao abrir.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        itemTab = new javax.swing.JTabbedPane();
        scrollItens = new javax.swing.JScrollPane();
        invLista = new javax.swing.JList<>();
        scrollPocoes = new javax.swing.JScrollPane();
        invPocoes = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtdinheiromochila = new javax.swing.JLabel();
        tabop = new javax.swing.JButton();
        btcomprarpocao = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtmov = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INVENTÁRIO");
        setMinimumSize(new java.awt.Dimension(330, 435));
        setPreferredSize(new java.awt.Dimension(330, 435));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        itemTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                itemTabStateChanged(evt);
            }
        });

        invLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        invLista.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        invLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        invLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                invListaValueChanged(evt);
            }
        });
        scrollItens.setViewportView(invLista);

        itemTab.addTab("Itens", scrollItens);

        invPocoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        invPocoes.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        invPocoes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        invPocoes.setPreferredSize(new java.awt.Dimension(38, 50));
        scrollPocoes.setViewportView(invPocoes);

        itemTab.addTab("Poções", scrollPocoes);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moeda_icon.png"))); // NOI18N
        jLabel2.setText("Dinheiro");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        txtdinheiromochila.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdinheiromochila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdinheiromochila.setText("0");
        jPanel3.add(txtdinheiromochila, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 48, 66, -1));

        tabop.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tabop.setText("Vender Item");
        tabop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tabopItemStateChanged(evt);
            }
        });
        tabop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabopActionPerformed(evt);
            }
        });
        jPanel3.add(tabop, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, -1));

        btcomprarpocao.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btcomprarpocao.setText("Comprar Poção");
        btcomprarpocao.setToolTipText("Custo de 100 moedas.");
        btcomprarpocao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btcomprarpocaoItemStateChanged(evt);
            }
        });
        btcomprarpocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcomprarpocaoActionPerformed(evt);
            }
        });
        jPanel3.add(btcomprarpocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtmov.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        txtmov.setText("Informativo de movimentação de itens.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(itemTab)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtmov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemTab, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmov, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(113, 113, 113))
        );

        itemTab.getAccessibleContext().setAccessibleName("Itens");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabopActionPerformed
        if (itemTab.getSelectedIndex() == 1) { // Verifica qual tab está selecionada.
            Mochila usarcura = new Mochila(); // Se estiver na tab de poções, botão usa cura.
            usarcura.usarcura();
        } else {
            Mochila venderitem = new Mochila(); // Se tab de itens, botão vende item.
            venderitem.venderItem();
        }
    }//GEN-LAST:event_tabopActionPerformed

    private void tabopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tabopItemStateChanged

    }//GEN-LAST:event_tabopItemStateChanged

    private void invListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_invListaValueChanged

    }//GEN-LAST:event_invListaValueChanged

    private void itemTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_itemTabStateChanged
        if (itemTab.getSelectedIndex() == 1) { // Verifica tab atual selecionada
            tabop.setText("Usar Poção"); // Se tab poções, troca textos para uso de itens.
            tabop.setToolTipText("Usar poção para recuperar vida.");
            tabop.setVisible(true);
            btcomprarpocao.setVisible(true);
        } else {
            tabop.setText("Vender Item"); // Se tab itens, troca textos para venda de itens.
            tabop.setToolTipText("Ganho de 50 moedas.");
            tabop.setVisible(true);
            btcomprarpocao.setVisible(false);
        }
    }//GEN-LAST:event_itemTabStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); // Fecha janela.
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btcomprarpocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcomprarpocaoActionPerformed
        Mochila comprarpocao = new Mochila(); // Ativa compra de poção, disponível apenas na tab de poções.
        comprarpocao.comprarpocao(0);
    }//GEN-LAST:event_btcomprarpocaoActionPerformed

    private void btcomprarpocaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btcomprarpocaoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btcomprarpocaoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMochila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuMochila dialog = new MenuMochila(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btcomprarpocao;
    public static javax.swing.JList<String> invLista;
    public static javax.swing.JList<String> invPocoes;
    private javax.swing.JTabbedPane itemTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollItens;
    private javax.swing.JScrollPane scrollPocoes;
    private static javax.swing.JButton tabop;
    public static javax.swing.JLabel txtdinheiromochila;
    public static javax.swing.JLabel txtmov;
    // End of variables declaration//GEN-END:variables
}
